register:
  number: 1
  max_workers: 1
  delete_low_balance_account: true
  delete_low_balance_account_threshold: 50
  email_server: 
    name: temp_email_server
    use_custom_address: false
    custom_email_address: 
    - email1@outlook.com
    - email2@outlook.com

  temp_email_server:
    name: Minuteinboxcom

  imap_email_server:
    imap_server: imap.qq.com
    imap_port: 993
    username: username
    password: password

oneapi:
  enabled: false
  url: http://localhost:3000
  token: your_oneapi_token
  channel_url: http://localhost:3010/
